<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/03/30 17:42:33

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=prueba',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
